[build]
command = "npm run build"
publish = "build"   # your Vite build is outputting to build/

[[redirects]]
  from = "/api/discover"
  to = "https://aidesignstudio.app.n8n.cloud/webhook/discover"
  status = 200
  force = true

